apiVersion: v1
kind: Service
metadata:
  name: swagger-app-service
  namespace: monitoring
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: swagger-app
    app.kubernetes.io/part-of: kube-prometheus
spec:
  selector:
    app: swagger-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-app
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: swagger-app
      app.kubernetes.io/part-of: kube-prometheus
  template:
    metadata:
      labels:
        app.kubernetes.io/component: exporter
        app.kubernetes.io/name: swagger-app
        app.kubernetes.io/part-of: kube-prometheus
    spec:
      containers:
        - name: swagger-app
          image: swagger-app:v1.0.0
          ports:
            - containerPort: 3000

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: swagger-app
    app.kubernetes.io/part-of: kube-prometheus
  name: swagger-app
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 30s
    path: /swagger-stats/metrics
    port: http
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: exporter
      app.kubernetes.io/name: swagger-app
      app.kubernetes.io/part-of: kube-prometheus