apiVersion: v1
kind: Service
metadata:
  name: prometheus-apps
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: apps
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    app: prometheus
    prometheus: apps