apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: monitoring
  labels:
    app: swagger
spec:
  selector:
    app: swagger
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger
  template:
    metadata:
      labels:
        app: swagger
    spec:
      containers:
        - name: swagger
          image: swagger-app:v1.0.0
          ports:
            - name: http
              containerPort: 3000